#this goes through the the original merged TMB data and recodes the countries of participants and investigates the distribution
list.files()
international.dat <- read.csv("merged_socper_adversity_tests_international_070214.csv")
head(international.dat)
str(international.dat[6])

str(international.dat[10])
unique(international.dat[,c("country")])
count(unique(international.dat[10]))
#139 unique countries in this data set
hist(international.dat[10])

library(ggplot2)
ggplot(data=international.dat, aes(geoip_country_code3)) + 
  geom_bar()



#north america
international.dat$geoip_country_code3 <- gsub("CAN", "NA", international.dat$geoip_country_code3, ignore.case = TRUE)
international.dat$geoip_country_code3 <- gsub("USA", "NA", international.dat$geoip_country_code3, ignore.case = TRUE)
international.dat$geoip_country_code3 <- gsub("CAN", "NA", international.dat$geoip_country_code3, ignore.case = TRUE)
international.dat$geoip_country_code3 <- gsub("PRI", "NA", international.dat$geoip_country_code3, ignore.case = TRUE)
international.dat$geoip_country_code3 <- gsub("VCT", "NA", international.dat$geoip_country_code3, ignore.case = TRUE)
international.dat$geoip_country_code3 <- gsub("CRI", "NA", international.dat$geoip_country_code3, ignore.case = TRUE)
international.dat$geoip_country_code3 <- gsub("DOM", "NA", international.dat$geoip_country_code3, ignore.case = TRUE)
international.dat$geoip_country_code3 <- gsub("JAM", "NA", international.dat$geoip_country_code3, ignore.case = TRUE)
international.dat$geoip_country_code3 <- gsub("BRB", "NA", international.dat$geoip_country_code3, ignore.case = TRUE)
international.dat$geoip_country_code3 <- gsub("GRD", "NA", international.dat$geoip_country_code3, ignore.case = TRUE)

#Europe
international.dat$geoip_country_code3 <- gsub("IRL", "EU", international.dat$geoip_country_code3, ignore.case = TRUE)
international.dat$geoip_country_code3 <- gsub("GBR", "EU", international.dat$geoip_country_code3, ignore.case = TRUE)
international.dat$geoip_country_code3 <- gsub("SWE", "EU", international.dat$geoip_country_code3, ignore.case = TRUE)
international.dat$geoip_country_code3 <- gsub("ROU", "EU", international.dat$geoip_country_code3, ignore.case = TRUE)
international.dat$geoip_country_code3 <- gsub("SRB", "EU", international.dat$geoip_country_code3, ignore.case = TRUE)
international.dat$geoip_country_code3 <- gsub("NLD", "EU", international.dat$geoip_country_code3, ignore.case = TRUE)
international.dat$geoip_country_code3 <- gsub("ESP", "EU", international.dat$geoip_country_code3, ignore.case = TRUE)
international.dat$geoip_country_code3 <- gsub("GRC", "EU", international.dat$geoip_country_code3, ignore.case = TRUE)
international.dat$geoip_country_code3 <- gsub("FRA", "EU", international.dat$geoip_country_code3, ignore.case = TRUE)
international.dat$geoip_country_code3 <- gsub("CYP", "EU", international.dat$geoip_country_code3, ignore.case = TRUE)
international.dat$geoip_country_code3 <- gsub("DEU", "EU", international.dat$geoip_country_code3, ignore.case = TRUE)
international.dat$geoip_country_code3 <- gsub("ITA", "EU", international.dat$geoip_country_code3, ignore.case = TRUE)
international.dat$geoip_country_code3 <- gsub("PRT", "EU", international.dat$geoip_country_code3, ignore.case = TRUE)
international.dat$geoip_country_code3 <- gsub("SVN", "EU", international.dat$geoip_country_code3, ignore.case = TRUE)
international.dat$geoip_country_code3 <- gsub("FIN", "EU", international.dat$geoip_country_code3, ignore.case = TRUE)
international.dat$geoip_country_code3 <- gsub("BGR", "EU", international.dat$geoip_country_code3, ignore.case = TRUE)
international.dat$geoip_country_code3 <- gsub("MNE", "EU", international.dat$geoip_country_code3, ignore.case = TRUE)
international.dat$geoip_country_code3 <- gsub("NOR", "EU", international.dat$geoip_country_code3, ignore.case = TRUE)
international.dat$geoip_country_code3 <- gsub("HRV", "EU", international.dat$geoip_country_code3, ignore.case = TRUE)
international.dat$geoip_country_code3 <- gsub("BLR", "EU", international.dat$geoip_country_code3, ignore.case = TRUE)
international.dat$geoip_country_code3 <- gsub("EST", "EU", international.dat$geoip_country_code3, ignore.case = TRUE)
international.dat$geoip_country_code3 <- gsub("BIH", "EU", international.dat$geoip_country_code3, ignore.case = TRUE)
international.dat$geoip_country_code3 <- gsub("POL", "EU", international.dat$geoip_country_code3, ignore.case = TRUE)
international.dat$geoip_country_code3 <- gsub("AUT", "EU", international.dat$geoip_country_code3, ignore.case = TRUE)
international.dat$geoip_country_code3 <- gsub("BEL", "EU", international.dat$geoip_country_code3, ignore.case = TRUE)
international.dat$geoip_country_code3 <- gsub("LTU", "EU", international.dat$geoip_country_code3, ignore.case = TRUE)
international.dat$geoip_country_code3 <- gsub("DNK", "EU", international.dat$geoip_country_code3, ignore.case = TRUE)
international.dat$geoip_country_code3 <- gsub("ALB", "EU", international.dat$geoip_country_code3, ignore.case = TRUE)
international.dat$geoip_country_code3 <- gsub("MDG", "EU", international.dat$geoip_country_code3, ignore.case = TRUE)
international.dat$geoip_country_code3 <- gsub("CZE", "EU", international.dat$geoip_country_code3, ignore.case = TRUE)
international.dat$geoip_country_code3 <- gsub("SVK", "EU", international.dat$geoip_country_code3, ignore.case = TRUE)
international.dat$geoip_country_code3 <- gsub("ISL", "EU", international.dat$geoip_country_code3, ignore.case = TRUE)
international.dat$geoip_country_code3 <- gsub("MLT", "EU", international.dat$geoip_country_code3, ignore.case = TRUE)
international.dat$geoip_country_code3 <- gsub("UKR", "EU", international.dat$geoip_country_code3, ignore.case = TRUE)
international.dat$geoip_country_code3 <- gsub("MKD", "EU", international.dat$geoip_country_code3, ignore.case = TRUE)
international.dat$geoip_country_code3 <- gsub("LVA", "EU", international.dat$geoip_country_code3, ignore.case = TRUE)
international.dat$geoip_country_code3 <- gsub("LUX", "EU", international.dat$geoip_country_code3, ignore.case = TRUE)
international.dat$geoip_country_code3 <- gsub("ANT", "EU", international.dat$geoip_country_code3, ignore.case = TRUE)
international.dat$geoip_country_code3 <- gsub("GIB", "EU", international.dat$geoip_country_code3, ignore.case = TRUE)
international.dat$geoip_country_code3 <- gsub("GEO", "EU", international.dat$geoip_country_code3, ignore.case = TRUE)
international.dat$geoip_country_code3 <- gsub("ALA", "EU", international.dat$geoip_country_code3, ignore.case = TRUE)


#south america
international.dat$geoip_country_code3 <- gsub("GTM", "SA", international.dat$geoip_country_code3, ignore.case = TRUE)
international.dat$geoip_country_code3 <- gsub("URY", "SA", international.dat$geoip_country_code3, ignore.case = TRUE)
international.dat$geoip_country_code3 <- gsub("PER", "SA", international.dat$geoip_country_code3, ignore.case = TRUE)
international.dat$geoip_country_code3 <- gsub("MEX", "SA", international.dat$geoip_country_code3, ignore.case = TRUE)
international.dat$geoip_country_code3 <- gsub("BRA", "SA", international.dat$geoip_country_code3, ignore.case = TRUE)
international.dat$geoip_country_code3 <- gsub("TTO", "SA", international.dat$geoip_country_code3, ignore.case = TRUE)
international.dat$geoip_country_code3 <- gsub("CHL", "SA", international.dat$geoip_country_code3, ignore.case = TRUE)
international.dat$geoip_country_code3 <- gsub("VEN", "SA", international.dat$geoip_country_code3, ignore.case = TRUE)
international.dat$geoip_country_code3 <- gsub("COL", "SA", international.dat$geoip_country_code3, ignore.case = TRUE)
international.dat$geoip_country_code3 <- gsub("ARG", "SA", international.dat$geoip_country_code3, ignore.case = TRUE)
international.dat$geoip_country_code3 <- gsub("HND", "SA", international.dat$geoip_country_code3, ignore.case = TRUE)
international.dat$geoip_country_code3 <- gsub("BOL", "SA", international.dat$geoip_country_code3, ignore.case = TRUE)
international.dat$geoip_country_code3 <- gsub("PAN", "SA", international.dat$geoip_country_code3, ignore.case = TRUE)
international.dat$geoip_country_code3 <- gsub("ECU", "SA", international.dat$geoip_country_code3, ignore.case = TRUE)


#asia
international.dat$geoip_country_code3 <- gsub("IND", "AS", international.dat$geoip_country_code3, ignore.case = TRUE)
international.dat$geoip_country_code3 <- gsub("IDN", "AS", international.dat$geoip_country_code3, ignore.case = TRUE)
international.dat$geoip_country_code3 <- gsub("JPN", "AS", international.dat$geoip_country_code3, ignore.case = TRUE)
international.dat$geoip_country_code3 <- gsub("JOR", "AS", international.dat$geoip_country_code3, ignore.case = TRUE)
international.dat$geoip_country_code3 <- gsub("TUR", "AS", international.dat$geoip_country_code3, ignore.case = TRUE)
international.dat$geoip_country_code3 <- gsub("CHN", "AS", international.dat$geoip_country_code3, ignore.case = TRUE)
international.dat$geoip_country_code3 <- gsub("BHR", "AS", international.dat$geoip_country_code3, ignore.case = TRUE)
international.dat$geoip_country_code3 <- gsub("ESP", "AS", international.dat$geoip_country_code3, ignore.case = TRUE)
international.dat$geoip_country_code3 <- gsub("MYS", "AS", international.dat$geoip_country_code3, ignore.case = TRUE)
international.dat$geoip_country_code3 <- gsub("LBN", "AS", international.dat$geoip_country_code3, ignore.case = TRUE)
international.dat$geoip_country_code3 <- gsub("ARE", "AS", international.dat$geoip_country_code3, ignore.case = TRUE)
international.dat$geoip_country_code3 <- gsub("PHL", "AS", international.dat$geoip_country_code3, ignore.case = TRUE)
international.dat$geoip_country_code3 <- gsub("ISR", "AS", international.dat$geoip_country_code3, ignore.case = TRUE)
international.dat$geoip_country_code3 <- gsub("SGP", "AS", international.dat$geoip_country_code3, ignore.case = TRUE)
international.dat$geoip_country_code3 <- gsub("PAK", "AS", international.dat$geoip_country_code3, ignore.case = TRUE)
international.dat$geoip_country_code3 <- gsub("HUN", "AS", international.dat$geoip_country_code3, ignore.case = TRUE)
international.dat$geoip_country_code3 <- gsub("IRA", "AS", international.dat$geoip_country_code3, ignore.case = TRUE)
international.dat$geoip_country_code3 <- gsub("VNM", "AS", international.dat$geoip_country_code3, ignore.case = TRUE)
international.dat$geoip_country_code3 <- gsub("AZE", "AS", international.dat$geoip_country_code3, ignore.case = TRUE)
international.dat$geoip_country_code3 <- gsub("LKA", "AS", international.dat$geoip_country_code3, ignore.case = TRUE)
international.dat$geoip_country_code3 <- gsub("SAU", "AS", international.dat$geoip_country_code3, ignore.case = TRUE)
international.dat$geoip_country_code3 <- gsub("KGZ", "AS", international.dat$geoip_country_code3, ignore.case = TRUE)
international.dat$geoip_country_code3 <- gsub("RUS", "AS", international.dat$geoip_country_code3, ignore.case = TRUE)
international.dat$geoip_country_code3 <- gsub("PSE", "AS", international.dat$geoip_country_code3, ignore.case = TRUE)
international.dat$geoip_country_code3 <- gsub("SYR", "AS", international.dat$geoip_country_code3, ignore.case = TRUE)
international.dat$geoip_country_code3 <- gsub("BGD", "AS", international.dat$geoip_country_code3, ignore.case = TRUE)
international.dat$geoip_country_code3 <- gsub("KOR", "AS", international.dat$geoip_country_code3, ignore.case = TRUE)
international.dat$geoip_country_code3 <- gsub("LAO", "AS", international.dat$geoip_country_code3, ignore.case = TRUE)
international.dat$geoip_country_code3 <- gsub("KWT", "AS", international.dat$geoip_country_code3, ignore.case = TRUE)
international.dat$geoip_country_code3 <- gsub("TWN", "AS", international.dat$geoip_country_code3, ignore.case = TRUE)
international.dat$geoip_country_code3 <- gsub("HKG", "AS", international.dat$geoip_country_code3, ignore.case = TRUE)
international.dat$geoip_country_code3 <- gsub("THA", "AS", international.dat$geoip_country_code3, ignore.case = TRUE)
international.dat$geoip_country_code3 <- gsub("NPL", "AS", international.dat$geoip_country_code3, ignore.case = TRUE)
international.dat$geoip_country_code3 <- gsub("BRN", "AS", international.dat$geoip_country_code3, ignore.case = TRUE)
international.dat$geoip_country_code3 <- gsub("MDA", "AS", international.dat$geoip_country_code3, ignore.case = TRUE)
international.dat$geoip_country_code3 <- gsub("IRN", "AS", international.dat$geoip_country_code3, ignore.case = TRUE)
international.dat$geoip_country_code3 <- gsub("ARM", "AS", international.dat$geoip_country_code3, ignore.case = TRUE)
international.dat$geoip_country_code3 <- gsub("BTN", "AS", international.dat$geoip_country_code3, ignore.case = TRUE)
international.dat$geoip_country_code3 <- gsub("KAZ", "AS", international.dat$geoip_country_code3, ignore.case = TRUE)
international.dat$geoip_country_code3 <- gsub("AFG", "AS", international.dat$geoip_country_code3, ignore.case = TRUE)
international.dat$geoip_country_code3 <- gsub("MWI", "AS", international.dat$geoip_country_code3, ignore.case = TRUE)
international.dat$geoip_country_code3 <- gsub("KHM", "AS", international.dat$geoip_country_code3, ignore.case = TRUE)
international.dat$geoip_country_code3 <- gsub("QAT", "AS", international.dat$geoip_country_code3, ignore.case = TRUE)
international.dat$geoip_country_code3 <- gsub("OMN", "AS", international.dat$geoip_country_code3, ignore.case = TRUE)
international.dat$geoip_country_code3 <- gsub("IO", "AS", international.dat$geoip_country_code3, ignore.case = TRUE)
international.dat$geoip_country_code3 <- gsub("YEM", "AS", international.dat$geoip_country_code3, ignore.case = TRUE)
international.dat$geoip_country_code3 <- gsub("IRQ", "AS", international.dat$geoip_country_code3, ignore.case = TRUE)

#austrailia
international.dat$geoip_country_code3 <- gsub("AUS", "AUS", international.dat$geoip_country_code3, ignore.case = TRUE)
international.dat$geoip_country_code3 <- gsub("NZL", "AUS", international.dat$geoip_country_code3, ignore.case = TRUE)
international.dat$geoip_country_code3 <- gsub("GUM", "AUS", international.dat$geoip_country_code3, ignore.case = TRUE)
international.dat$geoip_country_code3 <- gsub("TON", "AUS", international.dat$geoip_country_code3, ignore.case = TRUE)
international.dat$geoip_country_code3 <- gsub("FJI", "AUS", international.dat$geoip_country_code3, ignore.case = TRUE)
international.dat$geoip_country_code3 <- gsub("NCL", "AUS", international.dat$geoip_country_code3, ignore.case = TRUE)

#africa
international.dat$geoip_country_code3 <- gsub("EGY", "AFR", international.dat$geoip_country_code3, ignore.case = TRUE)
international.dat$geoip_country_code3 <- gsub("ZAF", "AFR", international.dat$geoip_country_code3, ignore.case = TRUE)
international.dat$geoip_country_code3 <- gsub("DZA", "AFR", international.dat$geoip_country_code3, ignore.case = TRUE)
international.dat$geoip_country_code3 <- gsub("CHE", "AFR", international.dat$geoip_country_code3, ignore.case = TRUE)
international.dat$geoip_country_code3 <- gsub("MAR", "AFR", international.dat$geoip_country_code3, ignore.case = TRUE)
international.dat$geoip_country_code3 <- gsub("KEN", "AFR", international.dat$geoip_country_code3, ignore.case = TRUE)
international.dat$geoip_country_code3 <- gsub("ETH", "AFR", international.dat$geoip_country_code3, ignore.case = TRUE)
international.dat$geoip_country_code3 <- gsub("MDG", "AFR", international.dat$geoip_country_code3, ignore.case = TRUE)
international.dat$geoip_country_code3 <- gsub("TUN", "AFR", international.dat$geoip_country_code3, ignore.case = TRUE)
international.dat$geoip_country_code3 <- gsub("MOZ", "AFR", international.dat$geoip_country_code3, ignore.case = TRUE)
international.dat$geoip_country_code3 <- gsub("MUS", "AFR", international.dat$geoip_country_code3, ignore.case = TRUE)
international.dat$geoip_country_code3 <- gsub("NGA", "AFR", international.dat$geoip_country_code3, ignore.case = TRUE)
international.dat$geoip_country_code3 <- gsub("LBY", "AFR", international.dat$geoip_country_code3, ignore.case = TRUE)
international.dat$geoip_country_code3 <- gsub("AFRM", "AFR", international.dat$geoip_country_code3, ignore.case = TRUE)
international.dat$geoip_country_code3 <- gsub("UGA", "AFR", international.dat$geoip_country_code3, ignore.case = TRUE)
international.dat$geoip_country_code3 <- gsub("SEN", "AFR", international.dat$geoip_country_code3, ignore.case = TRUE)
international.dat$geoip_country_code3 <- gsub("GMB", "AFR", international.dat$geoip_country_code3, ignore.case = TRUE)
international.dat$geoip_country_code3 <- gsub("SYC", "AFR", international.dat$geoip_country_code3, ignore.case = TRUE)
international.dat$geoip_country_code3 <- gsub("GHA", "AFR", international.dat$geoip_country_code3, ignore.case = TRUE)
international.dat$geoip_country_code3 <- gsub("NAM", "AFR", international.dat$geoip_country_code3, ignore.case = TRUE)

international.dat$geoip_country_code3<- as.factor(international.dat$geoip_country_code3)
class(international.dat$geoip_country_code3)
